version: "3"
services:
  develop:
    build: .
    ports:
      - "4200:4200"
    container_name: ct-ui
    env_file:
      - dev.env
    command: develop
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

