version: "3"
services:
  test:
    build: .
    ports:
      - "4200:4200"
    container_name: ct-ui-test
    environment:
      NODE_ENV: test
      PORT: 4200
      LOGGER_TYPE: console
      NODE_PATH: app/src
    command: test
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
